# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
def common_pods
  pod 'SnapKit', '~> 5.0.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'FlexibleModelProtocol', '~> 1.1'
  pod 'RealmSwift', '=10.1.4'
  pod 'FSPagerView'
end

target 'AppStoreClone' do
  common_pods
end

target 'AppStoreCloneTests' do
  common_pods
end
